#!/usr/bin/env bash

echo "Configuring user: $USER"
echo -n "Github user? [$USER] "
read GITHUB_USER

UNIX_USER="$USER"
GITHUB_USER="${GITHUB_USER:-$UNIX_USER}"

BASH_PATH=$(which bash)
CURL_PATH=$(which curl)

sudo adduser --system --disabled-password --no-create-home  --home "/nonexistent" --shell "$BASH_PATH" github-auth

sudo tee -a "/etc/ssh/sshd_config" > /dev/null << XXX
Match User $UNIX_USER
    AuthorizedKeysCommand $CURL_PATH -s "https://github.com/$GITHUB_USER.keys"
    AuthorizedKeysCommandUser github-auth
XXX

sudo systemctl restart ssh
